language: c
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
    global:
        - PACKAGE="mirage-xen"
    matrix:
        - OCAML_VERSION=4.11
        - OCAML_VERSION=4.10
        - OCAML_VERSION=4.09
        - OCAML_VERSION=4.08
